Desktop
kimitaWanjohi/my-portfolio pull request #4
Opened 2023-02-23 15:35 UTC by kimitaWanjohi

**Made the page responsive on a desktop screen by:**

- Adding media queries for 768px and 1024px.
- Styled section to fit the desktop screen.

2023-02-23 16:36 UTC, tufoinnkuo10 requested changes
Hi @kimitaWanjohi 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ great design

Required Changes ♻️
Check the comments under the review
- [ ] please remove the live demo section in your readme file since you don't yet have a deployed version of your application. this will make your readme more professional

![tufoin](https://media.giphy.com/media/GyejNZBefOIH1bqRTA/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-02-23 16:36 UTC, tufoinnkuo10 commented on index.html
> +            <!-- mobile nav -->
- [ ] kindly add some space between your headline  section and the navigation bar so it follows the original design
 yours
![Screenshot (830)_LI](https://user-images.githubusercontent.com/65298048/220961784-c7fa0e62-b808-445e-8d57-4af905ce5b65.jpg)
figma
![Screenshot (831)_LI](https://user-images.githubusercontent.com/65298048/220961977-9777f282-5bca-407b-b541-b1f422248d57.jpg)

2023-02-24 11:40 UTC, osamaashraf6 requested changes
Hi  @kimitaWanjohi ☺️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights ✔️

- [x] Good commit messages.
- [x] No linter errors. 💯
- [x] Good usage in correcting GitHub flow

 ## Required Changes ♻️

- kindly 😊 as stated by the previous reviewer, please remove the live demo section in your readme file since you don't yet have a deployed version of your application. this will make your readme more professional
- Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 11:40 UTC, osamaashraf6 commented on index.html
> +                        I'm always interested in hearing about new projects, so if you'd like to chat please get in touch.
- [ ] Kindly 😃 as stated by the previous reviewer please try as much as possible to follow the Figma design. kindly align the text and form of the contact section with the cards above it so it follows the Figma design
- [ ]  please kindly add the email field like in the original design. you can use one input field for the name if you wish( you can opmit the last name and use one input field for the name) but the email field should appear like in the original design.💯
- [ ] please 😊 the background image should be visible around the contact section like in the original design. remember you are practicing how to deliver what your customer will ask for in the future so the little details will matter. nice work.


> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Figma design | Your design| 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/83360636/221168773-719da877-717a-4b43-9d65-5ec1c1a04428.png)   |    ![image](https://user-images.githubusercontent.com/83360636/221168692-9f5540db-f7e0-4ca8-af1c-5f62ec856fce.png)   |

2023-02-24 11:40 UTC, osamaashraf6 commented on index.html
> +                            </div>
- [ ] [optional] please 😊 remember, you are supposed to stick to the design as much as possible. your mobile version contact form is different from the Figma version. the email under the social links is missing as well. kindly fix that.
yours💯

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Figma design | Your design| 
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/83360636/221169204-a24af74c-b218-4c0a-bedd-04a6d076497a.png)   |    ![image](https://user-images.githubusercontent.com/83360636/221169142-7aeab7b9-06b2-4b3f-a313-e9569e37f186.png) |

2023-02-24 11:40 UTC, osamaashraf6 commented on index.html
> +            <!-- mobile nav -->
- [ ] Kindly 😃 as stated by the previous reviewer kindly add some space between your headline section and the navigation bar so it follows the original design yours

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Figma design | Your design| 
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/83360636/221169619-1c0a6b2c-d4d4-4ddb-9f13-798a99139892.png)  |  ![image](https://user-images.githubusercontent.com/83360636/221169565-177acc5d-49a2-4f6e-822a-6fed26b2d278.png)  |

2023-02-24 12:42 UTC, divinecharlotte approved these changes
Hi @kimitaWanjohi  , 
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 12:46 UTC, merged